edition = "2018"
unstable_features = true

# fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
inline_attribute_width = 60
overflow_delimited_expr = true
reorder_impl_items = true
use_field_init_shorthand = true
